const enum Headwear {
  WhaleHead = "WHALE HEAD",
  RamenBowl = "RAMEN BOWL",
  Volcano = "VOLCANO",
  BirdNest = "BIRD NEST",
  RainbowAfro = "RAINBOW AFRO",
  NumberOneHat = "#1 HAT",
  Tricorne = "TRICORNE",
  PropellerHat = "PROPELLER HAT",
  MinerHat = "MINER HAT",
  Visor = "VISOR",
  BikeHelmet = "BIKE HELMET",
  Fedora = "FEDORA",
  Sweatband = "SWEATBAND",
  Pickelhaube = "PICKELHAUBE",
  Beanie = "BEANIE",
  BoonieHat = "BOONIE HAT",
  TrojanHelmet = "TROJAN HELMET",
  StrawHat = "STRAW HAT",
  FishermanHat = "FISHERMAN HAT",
  BaseballCap = "BASEBALL CAP",
  Deerstalker = "DEERSTALKER",
  TopHat = "TOP HAT",
}

const headwearRarities: Rarities = [
  [NONE, 0.38],
  [Headwear.WhaleHead, 0.0025],
  [Headwear.RamenBowl, 0.0025],
  [Headwear.Volcano, 0.0025],
  [Headwear.BirdNest, 0.0025],
  [Headwear.RainbowAfro, 0.01],
  [Headwear.NumberOneHat, 0.01],
  [Headwear.Tricorne, 0.01],
  [Headwear.PropellerHat, 0.01],
  [Headwear.MinerHat, 0.01],
  [Headwear.Visor, 0.04],
  [Headwear.BikeHelmet, 0.04],
  [Headwear.Fedora, 0.04],
  [Headwear.Sweatband, 0.04],
  [Headwear.Pickelhaube, 0.04],
  [Headwear.Beanie, 0.04],
  [Headwear.BoonieHat, 0.04],
  [Headwear.TrojanHelmet, 0.04],
  [Headwear.StrawHat, 0.04],
  [Headwear.FishermanHat, 0.04],
  [Headwear.BaseballCap, 0.04],
  [Headwear.Deerstalker, 0.04],
  [Headwear.TopHat, 0.04],
];
