const enum Mouthpiece {
  FrillyPartyBlower = "FRILLY PARTY BLOWER",
  SpaceVape = "SPACE VAPE",
  Cigar = "CIGAR",
  Rose = "ROSE",
  Pacifier = "PACIFIER",
  Kazoo = "KAZOO",
  Spoon = "SPOON",
  BambooShoot = "BAMBOO SHOOT",
  Harmonica = "HARMONICA",
  PartyBlower = "PARTY BLOWER",
  Gum = "GUM",
  Pipe = "PIPE",
  PieceOfStraw = "PIECE OF STRAW",
}

const mouthpieceRarities: Rarities = [
  [NONE, 0.645],
  [Mouthpiece.FrillyPartyBlower, 0.01],
  [Mouthpiece.SpaceVape, 0.0025],
  [Mouthpiece.Cigar, 0.0025],
  [Mouthpiece.Rose, 0.01],
  [Mouthpiece.Pacifier, 0.01],
  [Mouthpiece.Kazoo, 0.04],
  [Mouthpiece.Spoon, 0.04],
  [Mouthpiece.BambooShoot, 0.04],
  [Mouthpiece.Harmonica, 0.04],
  [Mouthpiece.PartyBlower, 0.04],
  [Mouthpiece.Gum, 0.04],
  [Mouthpiece.Pipe, 0.04],
  [Mouthpiece.PieceOfStraw, 0.04],
];
