const enum Clothing {
  NiftyHoodie = "NIFTY HOODIE",
  AstronautSuit = "ASTRONAUT SUIT",
  SmokingJacket = "SMOKING JACKET",
  TacticalVest = "TACTICAL VEST",
  LatexSuit = "LATEX SUIT",
  Wetsuit = "WETSUIT",
  HawaiianShirt = "HAWAIIAN SHIRT",
  TieDyeShirt = "TIE DYE SHIRT",
  LeatherJacket = "LEATHER JACKET",
  SpaghettiStrap = "SPAGHETTI STRAP",
  LooseTop = "LOOSE TOP",
  MeshShirt = "MESH SHIRT",
  Kimono = "KIMONO",
  CrewneckSweater = "CREWNECK SWEATER",
  ShaggySweater = "SHAGGY SWEATER",
  Dress = "DRESS",
  Suit = "SUIT",
  Hoodie = "HOODIE",
  Polo = "POLO",
  BandShirt = "BAND SHIRT",
  WhiteShirt = "WHITE SHIRT",
  TankTop = "TANK TOP",
  Blouse = "BLOUSE",
  CropTop = "CROP TOP",
}

const clothingRarities: Rarities = [
  [NONE, 0.38],
  [Clothing.NiftyHoodie, 0.0025],
  [Clothing.AstronautSuit, 0.0025],
  [Clothing.SmokingJacket, 0.0025],
  [Clothing.TacticalVest, 0.0025],
  [Clothing.LatexSuit, 0.01],
  [Clothing.Wetsuit, 0.01],
  [Clothing.HawaiianShirt, 0.01],
  [Clothing.TieDyeShirt, 0.01],
  [Clothing.LeatherJacket, 0.01],
  [Clothing.SpaghettiStrap, 0.04],
  [Clothing.LooseTop, 0.04],
  [Clothing.MeshShirt, 0.04],
  [Clothing.Kimono, 0.04],
  [Clothing.CrewneckSweater, 0.04],
  [Clothing.ShaggySweater, 0.04],
  [Clothing.Dress, 0.04],
  [Clothing.Suit, 0.04],
  [Clothing.Hoodie, 0.04],
  [Clothing.Polo, 0.04],
  [Clothing.BandShirt, 0.04],
  [Clothing.WhiteShirt, 0.04],
  [Clothing.TankTop, 0.04],
  [Clothing.Blouse, 0.04],
  [Clothing.CropTop, 0.04],
];
