const enum Neckwear {
  KingsNecklace = "KINGS NECKLACE",
  HawaiianLei = "HAWAIIAN LEI",
  EvilEyePendant = "EVIL EYE PENDANT",
  CrossPendant = "CROSS PENDANT",
  HeavySilverChain = "HEAVY SILVER CHAIN",
  HeavyGoldChain = "HEAVY GOLD CHAIN",
  Bandana = "BANDANA",
  Headphones = "HEADPHONES",
  Towel = "TOWEL",
  PoolNoodle = "POOL NOODLE",
  Bib = "BIB",
  Scarf = "SCARF",
  LeatherStrap = "LEATHER STRAP",
  Choker = "CHOKER",
  SharkNecklace = "SHARK NECKLACE",
  ShellNecklace = "SHELL NECKLACE",
  FineSilverChain = "FINE SILVER CHAIN",
  FineGoldChain = "FINE GOLD CHAIN",
  PearlNecklace = "PEARL NECKLACE",
}

const neckwearRarities: Rarities = [
  [NONE, 0.435],
  [Neckwear.KingsNecklace, 0.0025],
  [Neckwear.HawaiianLei, 0.0025],
  [Neckwear.EvilEyePendant, 0.01],
  [Neckwear.CrossPendant, 0.01],
  [Neckwear.HeavySilverChain, 0.01],
  [Neckwear.HeavyGoldChain, 0.01],
  [Neckwear.Bandana, 0.04],
  [Neckwear.Headphones, 0.04],
  [Neckwear.Towel, 0.04],
  [Neckwear.PoolNoodle, 0.04],
  [Neckwear.Bib, 0.04],
  [Neckwear.Scarf, 0.04],
  [Neckwear.LeatherStrap, 0.04],
  [Neckwear.Choker, 0.04],
  [Neckwear.SharkNecklace, 0.04],
  [Neckwear.ShellNecklace, 0.04],
  [Neckwear.FineSilverChain, 0.04],
  [Neckwear.FineGoldChain, 0.04],
  [Neckwear.PearlNecklace, 0.04],
];
