const enum Eyewear {
  TreeWizardSpectacles = "TREE WIZARD SPECTACLES",
  RoboticEye = "ROBOTIC EYE",
  PowerLevelScanner = "POWER LEVEL SCANNER",
  SleazySunglasses = "SLEAZY SUNGLASSES",
  VrGoggles = "VR GOGGLES",
  HypnoGlasses = "HYPNO GLASSES",
  SwimGoggles = "SWIM GOGGLES",
  SkiGoggles = "SKI GOGGLES",
  EyeMask = "EYE MASK",
  HeartSunglasses = "HEART SUNGLASSES",
  CateyeGlasses = "CATEYE GLASSES",
  PrinceNez = "PRINCE NEZ",
  Monocle = "MONOCLE",
  ThreeDGlasses = "3D GLASSES",
  Sunglasses = "SUNGLASSES",
  NerdGlasses = "NERD GLASSES",
}

const eyewearRarities: Rarities = [
  [NONE, 0.6],
  [Eyewear.TreeWizardSpectacles, 0.0025],
  [Eyewear.RoboticEye, 0.0025],
  [Eyewear.PowerLevelScanner, 0.0025],
  [Eyewear.SleazySunglasses, 0.01],
  [Eyewear.VrGoggles, 0.01],
  [Eyewear.HypnoGlasses, 0.04],
  [Eyewear.SwimGoggles, 0.04],
  [Eyewear.SkiGoggles, 0.04],
  [Eyewear.EyeMask, 0.04],
  [Eyewear.HeartSunglasses, 0.04],
  [Eyewear.CateyeGlasses, 0.04],
  [Eyewear.PrinceNez, 0.04],
  [Eyewear.Monocle, 0.04],
  [Eyewear.ThreeDGlasses, 0.04],
  [Eyewear.Sunglasses, 0.04],
  [Eyewear.NerdGlasses, 0.04],
];
